Django_Class_Base_View/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddView.as_view(), name='add'),
    path('posts/', views.PostView.as_view(), name='posts'),
    path('<slug:slug>/', views.SingleView.as_view(), name='single'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),

]

core/models.py
import urllib
from urllib import request

from django.db import models
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class Core(models.Model):
    title = models.CharField(max_length=200, )
    excerpt = models.TextField(null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='core')
    slug = models.SlugField(max_length=100, unique=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('core:single', args=[self.slug])

    class Meta:
        ordering = ['-published']

    def __str__(self):
        return self.title

core/forms.py
from django import forms
from .models import Core


class PostForm(forms.ModelForm):
    class Meta:
        model = Core
        fields = "__all__"

core/views.py
from django.urls import reverse_lazy

from .models import Core
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView


# Create your views here.
class IndexView(ListView):
    model = Core
    template_name = 'core/index.html'
    context_object_name = 'index'


class SingleView(DetailView):
    model = Core
    template_name = 'core/single.html'
    context_object_name = 'post'


class PostView(ListView):
    model = Core
    template_name = 'core/posts.html'
    context_object_name = 'post_list'

class AddView(CreateView):
    model = Core
    template_name = 'core/add.html'
    fields='__all__'
    success_url = reverse_lazy('core:posts')

class EditView(UpdateView):
    model = Core
    template_name = 'core/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')

class Delete(DeleteView):
    model = Core
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')
    template_name = 'core/confirm-delete.html'

templates/core/add.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="container pt-5">
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.lavel }}</label>
                    {{ field|add_class:'form-control' }}
                    {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            {% endfor %}
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-ok"></span> Save
                </button>
                <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
            </div>

        </form>
    </div>
{% endblock %}

templates/core/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Note App</title>
</head>
<body>
{% include 'core/navbar.html' %}
{% block content %}

{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
{% include 'core/footer.html' %}
</body>
</html>

templates/core/confirm-delete.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="container pt-5">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to Delete This?</p>
            <input type="submit" value="Confirm">
        </form>
    </div>
{% endblock %}

templates/core/edit.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="container pt-5">
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.lavel }}</label>
                    {{ field|add_class:'form-control' }}
                    {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            {% endfor %}
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-ok"></span> Edit
                </button>
                <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
            </div>

        </form>
    </div>
{% endblock %}

templates/core/footer.html
<div class="container">
    <footer class="pt-4 my-md-5 border-top">
        <div class="row">
            <div class="col-6 col-md">
            </div>
        </div>
    </footer>
</div>

templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for core in index %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body">
                                <h4 class=""><a href="{{ core.get_absolute_url }}">{{ core.title }}</a></h4>
                                <p>On {{ core.updated }}</p>
                                <p class="card-text"></p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="">
                                        <small class="text-muted"></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Notes App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:posts' %}">Manage Notes</a>
            </li>
        </ul>
        <button onclick="window.location.href='https://github.com/samir321-pixel'" target="_blank" class="btn btn-outline-success my-2 my-sm-0"  type="submit"> <i class="fa fa-github"> Github</i> </button>
    </div>
</nav>

templates/core/posts.html
{% extends 'core/base.html' %}
{% block content %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="navbar-brand">Notes Administration</div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="btn btn-outline-info my-2 my-sm-0" href="{% url 'core:add' %}">Add New Note</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for post in post_list %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body">
                                <h4 class=""><a href="{% url 'core:single' post.pk %}">{{ post.title }}</a></h4>
                                <p class="card-text"></p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{{ post.get_absolute_url }}" class="btn btn-sm btn-outline-primary" style="margin:5px;"
                                           role="button" aria-pressed="true">View</a>
                                        <a href="{% url 'core:edit' post.pk %}" class="btn btn-sm btn-outline-secondary"style="margin:5px;"
                                           role="button" aria-pressed="true">Edit</a>
                                        <a href="{% url 'core:delete' post.pk %}" class="btn btn-sm btn-outline-danger"style="margin:5px;"
                                           role="button" aria-pressed="true">Delete</a>

                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/core/single.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 pt-5">
                <h2 class="pt-5">{{ post.title }}</h2>
                <h5>Description: </h5>
                <div class="card">
                    <p>{{ post.excerpt }}</p>
                </div>
                <p>published on: {{ post.updated }} by Admin.</p>
            </div>
        </div>
    </div>
{% endblock %}